TipoTransacao.create({descricao: 'Débito', natureza: true})
TipoTransacao.create({descricao: 'Boleto'})
TipoTransacao.create({descricao: 'Financiamento'})
TipoTransacao.create({descricao: 'Crédito', natureza: true})
TipoTransacao.create({descricao: 'Recebimento Empréstimo', natureza: true})
TipoTransacao.create({descricao: 'Vendas', natureza: true})
TipoTransacao.create({descricao: 'Recebimento TED', natureza: true})
TipoTransacao.create({descricao: 'Recebimento DOC', natureza: true})
TipoTransacao.create({descricao: 'Aluguel'})

